name: Actions workflow

on: [push, pull_request]

jobs:
  run-ga:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
#          git clone git@github.com/$GITHUB_REPOSITORY
#          git checkout $GITHUB_SHA
      - name: Checkout
        uses: actions/checkout@v1
      - name: List files After Checkout
        run: |
          pwd
          ls -a
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Patrick
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"